version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # fastest allowed interval
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    reviewers:
      - "pranavgundu" # assigns you to review each PR
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
