#!/usr/bin/env node

import fs from "fs";
import { createRequire } from "module";

interface CommitInfo {
  sha: string;
  fullSha: string;
  message: string;
  author: string;
  date: string;
  url: string;
}

interface GitLastCommitData {
  shortHash: string;
  hash: string;
  subject: string;
  authoredOn: string;
  author: {
    name: string;
  };
}

type GetLastCommit = (
  callback: (error: Error | null, commit: GitLastCommitData | null) => void,
) => void;

const REPO_URL = "https://github.com/pranavgundu/Strategy-Board";

function toIsoDate(value: string): string {
  const unixSeconds = Number(value);
  if (Number.isFinite(unixSeconds) && unixSeconds > 0) {
    return new Date(unixSeconds * 1000).toISOString();
  }

  const parsed = new Date(value);
  if (!Number.isNaN(parsed.getTime())) {
    return parsed.toISOString();
  }

  return new Date().toISOString();
}

function getCommitInfo(): Promise<CommitInfo> {
  return new Promise((resolve, reject) => {
    const require = createRequire(import.meta.url);
    const gitLastCommit = require("git-last-commit") as {
      getLastCommit?: GetLastCommit;
    };

    if (typeof gitLastCommit.getLastCommit !== "function") {
      reject(new Error("git-last-commit did not expose getLastCommit"));
      return;
    }

    gitLastCommit.getLastCommit((error, commit) => {
      if (error || !commit) {
        reject(error ?? new Error("No commit data available"));
        return;
      }

      resolve({
        sha: commit.shortHash,
        fullSha: commit.hash,
        message: commit.subject,
        author: commit.author.name,
        date: toIsoDate(commit.authoredOn),
        url: `${REPO_URL}/commit/${commit.hash}`,
      });
    });
  });
}

function writeBuildInfo(commitInfo: CommitInfo): void {
  const content = `// Auto-generated by scripts/git.ts\nexport const BUILD_COMMIT = ${JSON.stringify(commitInfo, null, 2)};\n`;
  fs.writeFileSync("src/build.ts", content);
}

try {
  const commitInfo = await getCommitInfo();
  writeBuildInfo(commitInfo);
  console.log("Build info generated:", commitInfo.sha);
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  console.warn("Warning: Could not get git commit info:", errorMessage);

  const fallback: CommitInfo = {
    sha: "unknown",
    fullSha: "unknown",
    message: "Development build",
    author: "Unknown",
    date: new Date().toISOString(),
    url: REPO_URL,
  };

  writeBuildInfo(fallback);
  console.log("Build info generated (fallback)");
}
