<script lang="ts">
  import Modal from "./Modal.svelte";
  import { native } from "$lib/native/api";
  let { open, onImport, onClose }: { open: boolean; onImport: (eventKey: string, teamNumber: string) => Promise<void>; onClose: () => void } = $props();
  let eventKey = $state(""); let teamNumber = $state(""); let apiKey = $state(""); let hasApiKey = $state(false); let loading = $state(false); let error = $state("");
  $effect(() => { if (!open) return; error = ""; void native.tba.hasApiKey().then((value) => hasApiKey = value, () => hasApiKey = false); });
  async function submit() { loading = true; error = ""; try { if (apiKey.trim()) { await native.tba.setApiKey(apiKey.trim()); hasApiKey = true; } await onImport(eventKey.trim(), teamNumber.trim()); } catch (reason) { error = reason instanceof Error ? reason.message : "Could not import matches from The Blue Alliance."; } finally { loading = false; } }
</script>
<Modal {open} title="Import from The Blue Alliance" {onClose}><form onsubmit={(event) => { event.preventDefault(); void submit(); }}><header class="modal-header"><h2>Import from The Blue Alliance</h2></header><div class="modal-content stack"><p class="muted">Enter an event key to import its matches. Add a team number to import only that team’s schedule.</p><label class="form-label" for="tba-key">TBA API key <span class="muted">(optional)</span></label><input id="tba-key" class="input" bind:value={apiKey} type="password" placeholder={hasApiKey ? "A key is configured" : "Optional personal API key"} autocomplete="off" /><small class="muted">{hasApiKey ? "A TBA key is configured for this device." : "Strategy Board may use a configured shared key."}</small><label class="form-label" for="event-key">Event key</label><input id="event-key" class="input" bind:value={eventKey} placeholder="e.g. 2026nyro" autocomplete="off" /><label class="form-label" for="team-number">Team number <span class="muted">(optional)</span></label><input id="team-number" class="input" bind:value={teamNumber} inputmode="numeric" maxlength="5" placeholder="e.g. 834" autocomplete="off" />{#if error}<p class="form-error" role="alert">{error}</p>{/if}</div><footer class="modal-actions"><button type="button" class="button ghost" onclick={onClose}>Cancel</button><button type="submit" class="button primary" disabled={!eventKey.trim() || loading}>{loading ? "Importing…" : "Import matches"}</button></footer></form></Modal>
<style>.form-error{margin:0;color:#ffaaaa}.muted{display:block}</style>
